# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 340)
        MainWindow.setMinimumSize(QtCore.QSize(325, 340))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/imgs/shakespeare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_lineEdit.setText("")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout.addWidget(self.search_lineEdit)
        self.clear_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clear_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/imgs/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_pushButton.setIcon(icon1)
        self.clear_pushButton.setIconSize(QtCore.QSize(24, 20))
        self.clear_pushButton.setFlat(False)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout.addWidget(self.clear_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.language_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.language_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/imgs/us-es.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/imgs/es-us.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.language_pushButton.setIcon(icon2)
        self.language_pushButton.setIconSize(QtCore.QSize(64, 22))
        self.language_pushButton.setCheckable(True)
        self.language_pushButton.setObjectName("language_pushButton")
        self.horizontalLayout_2.addWidget(self.language_pushButton)
        self.searchtype_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.searchtype_comboBox.setObjectName("searchtype_comboBox")
        self.searchtype_comboBox.addItem("")
        self.searchtype_comboBox.addItem("")
        self.searchtype_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.searchtype_comboBox)
        self.exact_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.exact_checkBox.setObjectName("exact_checkBox")
        self.horizontalLayout_2.addWidget(self.exact_checkBox)
        spacerItem = QtWidgets.QSpacerItem(17, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.result_TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.result_TextEdit.setReadOnly(True)
        self.result_TextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.result_TextEdit.setObjectName("result_TextEdit")
        self.gridLayout.addWidget(self.result_TextEdit, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/imgs/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/imgs/acercaQT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Qt.setIcon(icon4)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.clear_pushButton.clicked.connect(self.search_lineEdit.clear)
        self.clear_pushButton.clicked.connect(self.result_TextEdit.clear)
        self.language_pushButton.clicked.connect(self.search_lineEdit.setFocus)
        self.exact_checkBox.clicked.connect(self.search_lineEdit.setFocus)
        self.clear_pushButton.clicked.connect(self.search_lineEdit.setFocus)
        self.searchtype_comboBox.activated['int'].connect(self.search_lineEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shakespeare"))
        self.clear_pushButton.setShortcut(_translate("MainWindow", "Alt+3", "Alt+Backspace"))
        self.language_pushButton.setShortcut(_translate("MainWindow", "Alt+1"))
        self.searchtype_comboBox.setItemText(0, _translate("MainWindow", "Starts with"))
        self.searchtype_comboBox.setItemText(1, _translate("MainWindow", "Ends with"))
        self.searchtype_comboBox.setItemText(2, _translate("MainWindow", "Contains"))
        self.exact_checkBox.setText(_translate("MainWindow", "Exact search"))
        self.exact_checkBox.setShortcut(_translate("MainWindow", "Alt+2"))
        self.result_TextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About Shakespeare"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
